# Generated by Django 3.0.6 on 2020-06-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_goals_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
